### ISSUE TITLE
submitting a new page to Reddit results in an API error

### ISSUE THREAD

**Issue by chilepeppers** [Kerrick/Mostly-Harmless#49] opened 2017-03-17 06:23 UTC
I've used this feature successfully about half a dozen times, but for most of the last year, it just tells me there was an API error while submitting and my submission history confirms that nothing completed the submission process.  This has occurred with more than a dozen submissions from different sources.

**Comment by Kerrick** [comment] 2017-03-17 15:35
It's entirely possible that reddit changed its API since I last updated the addon. Will look into this!

**Comment by speckz** [comment] 2017-03-17 15:38
This is a dupe of https://github.com/Kerrick/Mostly-Harmless/issues/47. And yes, Reddit API did change as per issue #47.

**Comment by Kerrick** [comment] 2017-03-17 15:51
Closing as duplicate of #47 - track that issue for updates @chilepeppers.

**Closed as completed by Kerrick** 2017-03-17 15:51 UTC
Labels: Level - Urgent, Type - Confirmed bug, Status - Duplicate
