### ISSUE TITLE
There was an API error. HTTP Status: 0. Click to try again.

### ISSUE THREAD

**Issue by BlindByrd** [Kerrick/Mostly-Harmless#48] opened 2015-08-26 02:37 UTC
Getting this error whenever I try to submit a page.

"There was an API error. HTTP Status: 0. Click to try again."

**Comment by speckz** [comment] 2015-08-27 12:20
Dupe of @ https://github.com/Kerrick/Mostly-Harmless/issues/47

**Closed as completed** 2015-08-30 01:57 UTC
Labels: Status - Duplicate
